### ISSUE TITLE
Hover styles et Boops

### ISSUE THREAD

**Issue by cogk** [boulets/PolitIF#22]
- [x] flèche bouton recherche (translation vers la droite)
- [x] ajouter style hover sur les ancres (:hover → text-decoration: none)
- [x] boop sur le .drapeau-francais
```css
.drapeau-francais:hover {
    animation: balancement 1s ease;
}
@keyframes balancement { 
  20% { transform: rotate(20deg); }
  40% { transform: rotate(-10deg); }
  60% { transform: rotate(5deg); }
  80% { transform: rotate(-5deg); }
  100% { transform: rotate(0deg); }
}
```
