### ISSUE TITLE
Indiquer qu'un lien est un lien externe

### ISSUE THREAD

**Issue by cogk** [boulets/PolitIF#74]
```css
a[href^="http://"]::after,
a[href^="https://"]::after {
  content: "[↗︎]";
  /* content: "🔗"; */
  text-decoration: none;
  
  vertical-align: super;
  font-size: 0.8em;
  line-height: 1;
/*
  position: relative;
  vertical-align: baseline;
  line-height: 0;
  font-size: 0.8em;
  top: -0.5em;
*/
}
```
